# Generated by Django 3.2.23 on 2024-01-24 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('status', models.IntegerField(default=0)),
                ('role', models.CharField(default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Addcustumer',
            fields=[
                ('Custumerid', models.AutoField(primary_key=True, serialize=False)),
                ('Custumer_name', models.CharField(max_length=100)),
                ('Custumer_mobile', models.CharField(max_length=100)),
                ('Delivery_date', models.DateField()),
                ('Serial_no', models.IntegerField(null=True)),
                ('Custumer_request', models.CharField(max_length=1000)),
                ('Current_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('Tailorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailorrecipt.user')),
            ],
        ),
    ]
