# Generated by Django 5.0.7 on 2024-10-08 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcustumer',
            fields=[
                ('Tailorid', models.IntegerField(default=1)),
                ('Custumerid', models.AutoField(primary_key=True, serialize=False)),
                ('Custumer_name', models.CharField(max_length=100)),
                ('Custumer_mobile', models.CharField(max_length=100)),
                ('Delivery_date', models.DateField()),
                ('Update', models.CharField(default='NOT UPDATED', max_length=100)),
                ('Serial_no', models.CharField(max_length=200, unique=True)),
                ('Current_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('Emailid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='clothbooking',
            fields=[
                ('Booking_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Mail_Id', models.CharField(max_length=100)),
                ('Mobile_No', models.BigIntegerField()),
                ('Upper_Wear', models.TextField()),
                ('Lower_Wear', models.TextField()),
                ('Description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date published')),
                ('Status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dueset',
            fields=[
                ('Custumerid', models.IntegerField()),
                ('Due_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('Due_amount', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachment_path', models.CharField(blank=True, max_length=500, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date published')),
                ('status', models.IntegerField(default=0)),
                ('role', models.CharField(default='custumer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lowerdetsils',
            fields=[
                ('Catid', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Fulllength', models.CharField(max_length=100)),
                ('Waist', models.CharField(max_length=100)),
                ('Hips', models.CharField(max_length=100)),
                ('Thigh', models.CharField(max_length=100)),
                ('Rise', models.CharField(max_length=100)),
                ('Knee', models.CharField(max_length=100)),
                ('Uplegoppening', models.CharField(max_length=100)),
                ('Legoppening', models.CharField(max_length=100)),
                ('Others', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
                ('Imageicon', models.CharField(max_length=200)),
                ('Custumerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailorrecipt.addcustumer')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentdetails',
            fields=[
                ('Recipt', models.AutoField(primary_key=True, serialize=False)),
                ('Totalamount', models.IntegerField()),
                ('Advanceamount', models.IntegerField()),
                ('Dueamount', models.IntegerField()),
                ('Custumerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailorrecipt.addcustumer')),
            ],
        ),
        migrations.CreateModel(
            name='Upperdetsils',
            fields=[
                ('Catid', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Frontlength', models.CharField(max_length=100)),
                ('Shoulder', models.CharField(max_length=100)),
                ('Chest', models.CharField(max_length=100)),
                ('Wrist', models.CharField(max_length=100)),
                ('Hips', models.CharField(max_length=100)),
                ('Sleeves', models.CharField(max_length=100)),
                ('Biseps', models.CharField(max_length=100)),
                ('Cuff', models.CharField(max_length=100)),
                ('Callor', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
                ('Imageicon', models.CharField(max_length=200)),
                ('Custumerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailorrecipt.addcustumer')),
            ],
        ),
    ]
