# Generated by Django 3.2.23 on 2024-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustumer',
            name='Serial_no',
            field=models.CharField(default=1001, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
