# Generated by Django 3.2.23 on 2024-01-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0002_alter_addcustumer_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcustumer',
            name='Custumer_request',
        ),
    ]
