# Generated by Django 3.2.23 on 2024-01-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0003_remove_addcustumer_custumer_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upperdetsils',
            fields=[
                ('Catid', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Frontlength', models.CharField(max_length=100)),
                ('Shoulder', models.CharField(max_length=100)),
                ('Chest', models.CharField(max_length=100)),
                ('Wrist', models.CharField(max_length=100)),
                ('Hips', models.CharField(max_length=100)),
                ('Sleeves', models.CharField(max_length=100)),
                ('Biseps', models.CharField(max_length=100)),
                ('Cuff', models.CharField(max_length=100)),
                ('Callor', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
                ('Imageicon', models.CharField(max_length=200)),
                ('Custumerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailorrecipt.user')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentdetails',
            fields=[
                ('Recipt', models.AutoField(primary_key=True, serialize=False)),
                ('Totalamount', models.IntegerField()),
                ('Advanceamount', models.IntegerField()),
                ('Dueamount', models.IntegerField()),
                ('Custumerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailorrecipt.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lowerdetsils',
            fields=[
                ('Catid', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Fulllength', models.CharField(max_length=100)),
                ('Waist', models.CharField(max_length=100)),
                ('Hips', models.CharField(max_length=100)),
                ('Thigh', models.CharField(max_length=100)),
                ('Rise', models.CharField(max_length=100)),
                ('Knee', models.CharField(max_length=100)),
                ('Uplegoppening', models.CharField(max_length=100)),
                ('Legoppening', models.CharField(max_length=100)),
                ('Others', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
                ('Imageicon', models.CharField(max_length=200)),
                ('Custumerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailorrecipt.user')),
            ],
        ),
    ]
