# Generated by Django 3.2.23 on 2024-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0005_auto_20240204_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustumer',
            name='Update',
            field=models.CharField(default='NOT UPDATED', max_length=100),
        ),
    ]
