# Generated by Django 5.0.6 on 2024-06-14 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0006_addcustumer_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueset',
            fields=[
                ('Custumerid', models.IntegerField()),
                ('Due_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('Due_amount', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
