# Generated by Django 5.0.6 on 2024-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0007_dueset'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustumer',
            name='Emailid',
            field=models.CharField(default='naveenpatidar12.linuxbean@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='custumer', max_length=10),
        ),
    ]
