# Generated by Django 5.0.6 on 2024-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0008_addcustumer_emailid_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustumer',
            name='Emailid',
            field=models.CharField(max_length=50),
        ),
    ]
