# Generated by Django 5.0.6 on 2024-07-19 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0009_alter_addcustumer_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustumer',
            name='Serial_no',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date published'),
        ),
    ]
