# Generated by Django 5.0.7 on 2024-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0012_emailstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustumer',
            name='Tailorid',
            field=models.IntegerField(default=1),
        ),
    ]
