# Generated by Django 5.0.6 on 2024-09-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0013_alter_addcustumer_tailorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
