# Generated by Django 5.0.6 on 2024-10-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0015_clothbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothbooking',
            name='Mobile_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clothbooking',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
