# Generated by Django 5.0.6 on 2024-10-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0016_alter_clothbooking_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothbooking',
            name='Mobile_No',
            field=models.BigIntegerField(),
        ),
    ]
