# Generated by Django 5.0.6 on 2024-10-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorrecipt', '0017_alter_clothbooking_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothbooking',
            name='Mail_Id',
            field=models.CharField(max_length=100),
        ),
    ]
